### ISSUE TITLE
Cannot see the upload status

### ISSUE THREAD

**Issue by cuecue123** [davidread/ckanext-shift#20]
Shift only allow user to view the data after the upload is completed. So when we are trying to upload a large file, such as the 311 services request file on data.boston.gov, which is 500+ MB large, we have need to wait for a long time before we can see any data. So there may be some issues if there's no log file that indicates the uploading status.

**Comment by davidread** [comment]
Initially this is shown:
<img width="870" alt="screen shot 2017-10-27 at 14 48 41" src="https://user-images.githubusercontent.com/307612/32107485-a13d5eca-bb26-11e7-8a3c-29e9e0d4aac8.png">

Then within a minute it shows the load has started:
<img width="908" alt="screen shot 2017-10-27 at 14 49 51" src="https://user-images.githubusercontent.com/307612/32107484-a10bffec-bb26-11e7-9561-c279465009a1.png">

Then when it's finished it shows a bit more.

This is what you should expect - is that what you saw @cuecue123 ?

BTW which site did you test? Boston sandbox site wasn't uploading this week due to a temporary hack. I've just fixed that, so maybe this is related.

**Comment by cuecue123** [comment]
I tested on my local, and and I saw the log file in my terminal. I think there are some issues with my datastore extensions because when I changed data pusher to shift, the datastore tab where I can view the log file disappeared on the website. 

And I just checked on the Bostonsandbox site, it works perfectly. Thanks.

**Comment by cuecue123** [comment]
I figured out the reason why the datastore tab is hidden is because I'm using the different version of CKAN. I will close this issue. Thanks.

**Comment by davidread** [comment]
It should display in the same as the DataStore tab did for the DataPusher
code. So if there is a difference in a particular CKAN version or due to
another extension, than I’d be pleased to investigate.
